import { Metadata } from "next";
import React, { ReactNode } from "react";

export const metadata: Metadata = {
  title: {
    default: " Products : Next App",
    absolute: "",
  },
  description: "Generated by create next app",
};

interface ProductLayoutProps {
  children: ReactNode;
}

const ProductLayout: React.FC<ProductLayoutProps> = async ({ children }) => {
  return (
    <React.Fragment>
      <main className="p-1 bg-slate-950 rounded">
        <h3 className="text-center p-3 mt-4 text-3xl font-semibold font-mono text-green-500 underline underline-offset-8 decoration-amber-500">
          Products
        </h3>
        {children}
      </main>
    </React.Fragment>
  );
};

export default ProductLayout;
